# Generated by Django 5.0.6 on 2024-06-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
